### ISSUE TITLE
Not work with PostCSS 8.2.8 as a Rollup plugin

### ISSUE THREAD

**Issue by duongdominhchau** [postcss/autoprefixer#1400]
## Description
I don't know whether it work in other cases or not, but when I use it with Rollup, I always get this error:

```
[!] (plugin postcss) TypeError: node.getIterator is not a function
src/global.scss
TypeError: node.getIterator is not a function
    at LazyResult.visitTick (/home/chau/web/node_modules/.pnpm/postcss@8.2.8/node_modules/postcss/lib/lazy-result.js:484:33)
    at LazyResult.runAsync (/home/chau/web/node_modules/.pnpm/postcss@8.2.8/node_modules/postcss/lib/lazy-result.js:372:30)
```

## Steps to reproduce
My project is messy, but I have successfully reproduced it in a minimal example here. I tried both `pnpm` and `npm` (by removing the `node_modules` and rerun `install` command) on this example, both result in the error above.

Create the project and add dependencies:

```sh
pnpm init --yes
pnpm add -D @csstools/postcss-sass autoprefixer postcss rollup rollup-plugin-postcss sass
```

Then create the files:

```js
// index.js
import './src/global.scss';

// rollup.config.js
import postcss from 'rollup-plugin-postcss';
import postcssSass from '@csstools/postcss-sass';
import autoprefixer from 'autoprefixer';

export default {
  input: 'index.js',
  output: {
    format: 'iife',
    name: 'app',
    file: 'bundle.js',
  },
  plugins: [
    postcss({
      extract: 'global.css',
      plugins: [postcssSass, autoprefixer],
    }),
  ],
};
```

```scss
// src/global.scss
@use 'example.scss';

body {
  margin: 0;
  padding: 0;
}

// src/example.scss
.autoplacement-example {
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-template-rows: auto auto;
  grid-gap: 20px;
}
```

Finally run `npx rollup -c` or `pnpx rollup -c` and the error appears.

## Versions
- @csstools/postcss-sass: 4.0.0
- autoprefixer: 10.2.5_postcss@8.2.8
- postcss: 8.2.8
- rollup: 2.41.1
- rollup-plugin-postcss: 4.0.0_postcss@8.2.8
- sass: 1.32.8

**Comment by ai** [comment]
Can you show `npm ls | grep postcss` output?

**Comment by duongdominhchau** [comment]
Here it is
```
├── @csstools/postcss-sass@4.0.0
├── postcss@8.2.8
├── rollup-plugin-postcss@4.0.0
```

**Comment by ai** [comment]
Very strange. `node.getIterator is not a function` error could happen only if AST is broken and contain PostCSS 7 nodes.

Maybe `@csstools/postcss-sass` generates something bad. Can you compile Sass sources to CSS and then try Autoprefixer without `@csstools/postcss-sass`?

**Comment by duongdominhchau** [comment]
Seem like `@csstools/postcss-sass` is causing the problem. I have just looked at their repo and see an issue about that plugin does not work with PostCSS 8. However, before I add `autoprefixer` to PostCSS plugins list, it does correctly compile, so when the problem occured I didn't think the fault is from that plugin, I apologize.
